@use('App\Enums\Role')

<x-slot:header>
    <div class="flex items-center justify-between">
        <h2 class="font-semibold text-xl text-gray-800 dark:text-gray-200 leading-tight">
            {{ __('Users') }}
        </h2>
        
        <x-primary-button x-on:click="$dispatch('open-form', 'form-user')">
            {{ __('See Form') }}
        </x-primary-button>
    </div>
</x-slot>

    
<x-shell.page class="flex flex-col gap-8" x-data
{{-- x-on:updated-user.window="$dispatch('close-form', 'form-user'); setTimeout(() => $dispatch('open-modal', 'password-generation'), 100)" --}}
>
    <x-modal name="password-generation" :show="isset($form->generated_password)" focusable>
        <div class="p-6">
            <h2 class="text-lg font-medium text-gray-900 dark:text-gray-100">
                {{ __('Password generated!') }}
            </h2>

            <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">
                {{ __('The following autogenerated password would allow the user enter the system.') }}
            </p>

            <div class="mt-6">
                <x-input-label for="password" value="{{ __('Password') }}" class="sr-only" />
                <x-input-clipboard :content="$form->generated_password"></x-input-clipboard>
            </div>

            <div class="mt-6 flex justify-end">
                <x-secondary-button x-on:click="$dispatch('close')">
                    {{ __('Close') }}
                </x-secondary-button>
            </div>
        </div>
    </x-modal>

    <x-form.user name="form-user" :$form/>

    @if (count($users) == 0)
        <x-empty.user>
            <x-primary-button x-on:click="showUserForm = true">
                {{ __('Add Users') }}
            </x-primary-button>
        </x-empty>
    @else 
        <x-table :columns="['Clave', 'Email', 'Nombre', 'Rol', 'Acciones']">
            @foreach ($users as $user)
                <x-table.row x-data="{{ json_encode(['role' => __($user->role->value)]) }}"
                x-on:role-updated="role === $event.detail.translated || 
                (role = $event.detail.translated, $wire.updateRole({{ $user->id }}, $event.detail.value))"
                >
                    <x-table.column>{{ $user->key }}</x-table>
                    <x-table.column>{{ $user->email }}</x-table>
                    <x-table.column>{{ $user->name }}</x-table>
                    <x-table.column >
                        <x-dropdown>
                            <x-slot:trigger>
                                <button 
                                x-text="role"
                                type="button"></button>
                            </x-slot>
                            <x-slot:content>
                                @foreach (Role::cases() as $role)
                                    <x-dropdown-link class="cursor-pointer" x-on:click="
                                    $dispatch('role-updated', {value: '{{ $role->value }}', 'translated': '{{ __($role->value) }}'});">
                                        {{ __($role->value) }}
                                    </x-dropdown-link>
                                @endforeach
                            </x-slot>
                        </x-dropdown>
                    </x-table>
                    <x-table.column class="flex gap-2 items-center justify-center">
                        <x-primary-button 
                        wire:click="proxyAction('load', {{ $user->id }})"
                        >
                            <x-heroicon-s-pencil class="w-4 h-4"/>
                        </x-secondary-button>
                        <x-danger-button 
                        wire:confirm="{{ __('Are you sure you want to delete this user?') }}"
                        wire:click="proxyAction('delete', {{ $user->id }})"
                        >
                            <x-heroicon-s-trash class="w-4 h-4"/>
                        </x-danger-button>
                    </x-table>
                </x-table>
            @endforeach
        </x-table>

        <div>
            {{ $users->links() }}
        </div>
    @endif
</x-shell>
            